config/routes.rb
Rails.application.routes.draw do
  resources :welcomes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcomes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def welcome_params
      params.fetch(:welcome, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcomes/_form.html.erb
<%= form_with(model: welcome, local: true) do |form| %>
  <% if welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcomes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @welcomes.each do |welcome| %>
      <tr>
        <td><%= link_to 'Show', welcome %></td>
        <td><%= link_to 'Edit', edit_welcome_path(welcome) %></td>
        <td><%= link_to 'Destroy', welcome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Welcome', new_welcome_path %>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>